"""initial_migration

Revision ID: 6d1372630993
Revises: 
Create Date: 2022-08-30 16:52:52.445312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1372630993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vlp',
    sa.Column('id', sa.String(), nullable=False, comment='Идентификатор записи'),
    sa.Column('q_list', sa.ARRAY(sa.Float()), nullable=True, comment='Массив дебитов жидкости'),
    sa.Column('p_wf', sa.ARRAY(sa.Float()), nullable=True, comment='Массив забойных давлений'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('well_data',
    sa.Column('id', sa.String(), nullable=False, comment='Идентификатор записи'),
    sa.Column('inclinometry', sa.String(), nullable=True, comment='Инклинометрия скважины в формате MD, TVD'),
    sa.Column('casing', sa.Float(), nullable=True, comment='Данные по Эксплуатационной Колонне'),
    sa.Column('tubing', sa.String(), nullable=True, comment='Данные по Колонне Насосно-Компрессорных Труб'),
    sa.Column('pvt', sa.String(), nullable=True, comment='Данные по флюидам'),
    sa.Column('p_wh', sa.Integer(), nullable=True, comment='Буферное давление, атм'),
    sa.Column('geo_grad', sa.Integer(), nullable=True, comment='Геотермический градиент, C/100 м'),
    sa.Column('h_res', sa.Integer(), nullable=True, comment='Глубина верхних дыр перфорации, м'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('well_data')
    op.drop_table('vlp')
    # ### end Alembic commands ###
