"""initial_migration

Revision ID: 7fbb0c937fc7
Revises: 
Create Date: 2022-08-07 17:19:02.689779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fbb0c937fc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well_data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('inclinometry', sa.JSON(), nullable=True, comment='Инклинометрия'),
    sa.Column('d_cas', sa.Float(), nullable=True, comment='Диаметр ЭК, м'),
    sa.Column('d_tub', sa.Float(), nullable=True, comment='Диаметр НКТ, м'),
    sa.Column('h_tub', sa.Float(), nullable=True, comment='Глубина спуска НКТ, м'),
    sa.Column('wct', sa.Float(), nullable=True, comment='Обводненность, %'),
    sa.Column('rp', sa.Float(), nullable=True, comment='Газовый фактор, м3/т'),
    sa.Column('gamma_oil', sa.Float(), nullable=True, comment='Плотность нефти'),
    sa.Column('gamma_gas', sa.Float(), nullable=True, comment='Плотность газа'),
    sa.Column('gamma_wat', sa.Float(), nullable=True, comment='Плотность воды'),
    sa.Column('t_res', sa.Float(), nullable=True, comment='Температура пласта, С'),
    sa.Column('p_wh', sa.Float(), nullable=True, comment='Буферное давление, атм'),
    sa.Column('geo_grad', sa.Float(), nullable=True, comment='Температурный градиент, С/100 м'),
    sa.Column('h_res', sa.Float(), nullable=True, comment='Глубина верхних дыр перфорации, м'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_well_data_id'), 'well_data', ['id'], unique=False)
    op.create_table('vlp',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('vlp', sa.JSON(), nullable=True, comment='VLP'),
    sa.Column('data_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['well_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlp_id'), 'vlp', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vlp_id'), table_name='vlp')
    op.drop_table('vlp')
    op.drop_index(op.f('ix_well_data_id'), table_name='well_data')
    op.drop_table('well_data')
    # ### end Alembic commands ###
