version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres-test-app
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: superuser
    ports:
      - "5432:5432"