name: Test Python App

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Postgres
      working-directory: ./docker/
      run: docker-compose -f docker-compose.yml up -d

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        alembic upgrade head
      env:
        PG_USER: vlp
        PG_PASS: vlp
        PG_DB: vlp
      working-directory: .

    - name: Test with pytest
      working-directory: ./src
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest